/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.3")
    implementation("org.apache.tomcat.embed:tomcat-embed-jasper:9.0.65")
    implementation("javax.servlet:jstl:1.2")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.7.3")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.7.3")
    implementation("org.mindrot:jbcrypt:0.4")
    implementation("org.webjars:webjars-locator:0.30")
    implementation("org.webjars:bootstrap:5.0.1")
    implementation("org.webjars:jquery:3.6.0")
    runtimeOnly("mysql:mysql-connector-java:8.0.30")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.3")
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
description = "goldenWastedd"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
